version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "linebot-shop-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iasolxxv392z"
s3_prefix = "linebot-shop-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
