AWSTemplateFormatVersion: 2010-09-09
Description: >-
  linebot shop app v1.0

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        STAGE: PROD
        TABLE_NAME: SampleTable
        PRODUCTS: Products
        GROUP_ID: C0aaadacda65271ee8760524e669d452c
        ADMIN_KEY: 123

Resources:
  healthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/health_check.healthCheckHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Health Check API
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/
            Method: GET

  getTodayProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get_products.getProductsHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get Today Product API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/product/
            Method: GET

  getProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get_products.getProductsHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get Product By date API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/product/{date}
            Method: GET

  putProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put_products.putProductsHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Put Today Product API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/product/
            Method: POST

  getTodayOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get_orders.getOrdersHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get Today Orders API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/order/
            Method: GET

  getOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get_orders.getOrdersHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get Orders By Date API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/order/{date}
            Method: GET

  orderProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/order_products.orderProductsHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Order Today Product API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/order/
            Method: POST

  parseMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/parse_messages.parseMessagesHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Parse Line Message API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/line/
            Method: POST

  SampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: date
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: date
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 20

Outputs:
  WebEndpoint:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
