AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  healthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/health_check.healthCheckHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Health Check API
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/
            Method: GET

  getProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get_products.getProductsHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get Product By date API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/product/{date}
            Method: GET
    
  putProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put_products.putProductsHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Put Today Product API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/product/
            Method: PUT
  
  orderProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/order_products.orderProductsHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Order Today Product API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/order/
            Method: PUT

  parseMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/parse_messages.parseMessagesHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Parse Line Message API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/order/
            Method: POST

  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: date
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
